export interface Player {
  id: string;
  name: string;      // Artistic or descriptive real name, e.g., "El 10 de Argentina"
  realName: string;  // Factual football name (e.g., L. Messi, Vinicius Jr)
  country: string;
  age: number;
  weight: number;    // kg
  height: number;    // cm
  dominantFoot: 'Izquierdo' | 'Derecho' | 'Ambidiestro';
  currentClub: string;
  rating: number;    // 0-100
  styleOfPlay: string; // Description generated by IA or scout
  position: 'GK' | 'DF' | 'MF' | 'FW';
  subPosition: string; // e.g. "Lateral Izquierdo", "Extremo Invertido"
  imageSeed: string; // used for generating cool avatars/cards
  imageUrl?: string; // Optional player card photo image (Sticker!)
  nickname?: string; // Apodo del jugador, ej. "La Pulga"
  shirtNumber?: number; // Número en camiseta
  actionAnimation?: string; // Descripción detallada de la acción animada (cromo digital)
  descriptiveTitle?: string; // Título descriptivo, ej. "El Astro argentino"
}

export interface TriviaQuestion {
  id: number;
  pregunta: string;
  opciones: string[];
  correcta: string;
}

export interface CountryTrivia {
  pais: string;
  nivel: number;
  preguntas: TriviaQuestion[];
}

export interface Match {
  id: string;
  local: string;
  visitante: string;
  fecha: string;
  grupo: string;
  marcadorReal?: { golesLocal: number; golesVisitante: number };
  onceInicialReal: string[]; // List of player IDs in the official starting XI
  jugado: boolean;
}

export interface UserPrediction {
  matchId: string;
  golesLocal: number;
  golesVisitante: number;
}

export interface UserTacticalBoard {
  country: string;
  formation: string; // '4-3-3' | '4-4-2' | '3-5-2' | '5-3-2'
  selectedPlayers: { [positionLabel: string]: string | null }; // positionLabel (e.g. "GK", "CB1") -> Player.id
  prediction: UserPrediction | null;
  predictionEligible?: boolean;
  predictionSavedAt?: string;
  predictionReason?: string;
}

export interface LeaderboardEntry {
  username: string;
  score: number;
  aciertosOnce: number; // count of matches in starting XI
  aciertosMarcador: number; // count of exact scores predicted
  avatar: string;
}

export interface User {
  id: string;               // ID único autogenerado o de auth
  gameCode: string;         // Código de juego único de 6 caracteres (ej: DT-2026)
  unlockedStickers: string[]; // Lista de IDs de los cromos individuales desbloqueados (ej. ["ar-1", "br-10"])
  completedCountries: string[]; // Lista de nombres de países completados (que desbloquearon sus 26 cromos)
  unlockedStickersCount: number; // Cantidad total de cromos desbloqueados (coincide con unlockedStickers.length)
  totalScore: number;       // Puntaje acumulado dinámico: (cantidad cromos * 1) + (países completos * 5)
  raffleEligibility?: '$1.000 USD (1er Lugar)' | '$500 USD (2do Lugar)' | '$250 USD (3er Lugar)' | 'Ninguno';
}

export function getCountryOfPlay(clubStr: string): string {
  if (!clubStr) return "Sin Equipo";
  
  // Extract content inside parenthesis if exists, e.g. "Real Madrid (ESP)" -> "ESP"
  const parenMatch = clubStr.match(/\(([^)]+)\)/);
  const code = parenMatch ? parenMatch[1].toUpperCase() : "";

  const countryMap: { [key: string]: string } = {
    ESP: "España",
    FRA: "Francia",
    ARG: "Argentina",
    ENG: "Inglaterra",
    USA: "Estados Unidos",
    GER: "Alemania",
    ITA: "Italia",
    POR: "Portugal",
    BRA: "Brasil",
    TUR: "Turquía",
    KSA: "Arabia Saudita",
    RUS: "Rusia",
    CYP: "Chipre",
    MEX: "México",
    NED: "Países Bajos",
    BEL: "Bélgica",
    GRE: "Grecia",
    COL: "Colombia",
    JPN: "Japón",
    SCO: "Escocia",
    MAR: "Marruecos",
    ALG: "Argelia",
    SUI: "Suiza",
    TUN: "Túnez",
    AUT: "Austria",
    CZE: "República Checa",
    DEN: "Dinamarca",
    WAL: "Gales",
    SRB: "Serbia",
    BIH: "Bosnia",
    KAZ: "Kazajistán",
    CRO: "Croacia",
    ROU: "Rumania",
    UAE: "EAU",
    IRL: "Irlanda",
    BUL: "Bulgaria",
    HUN: "Hungría",
    ISR: "Israel",
    EGY: "Egipto",
    QAT: "Catar",
    CAN: "Canadá",
    ECU: "Ecuador"
  };

  if (code && countryMap[code]) {
    return `${countryMap[code]} (${code})`;
  }

  if (code) {
    return `Liga ${code}`;
  }

  // Check if string contains country codes without parenthesis, e.g. "Chelsea FC ENG"
  for (const [abbr, name] of Object.entries(countryMap)) {
    if (clubStr.toUpperCase().endsWith(` ${abbr}`) || clubStr.toUpperCase().includes(` ${abbr} `)) {
      return `${name} (${abbr})`;
    }
  }

  if (clubStr.toLowerCase().includes("libre") || clubStr.toLowerCase().includes("sin equipo")) {
    return "Agente Libre";
  }

  return "Liga Internacional";
}

export interface BlogPost {
  id: string;
  title: string;
  content: string;
  imageUrl?: string;
  createdAt: string;
}

export interface Suggestion {
  id: string;
  username: string;
  email: string;
  suggestion: string;
  sentTo: string;
  createdAt: string;
  status: 'pending' | 'reviewed';
}



